on:
  pull_request:
   types: [labeled]

jobs:
  request_colony:
    name: Request a new colony when PR is labeled with 'beehive'
    if: contains(github.event.pull_request.labels.*.name, 'beehive')
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: |
        echo "${{ toJson(github.event.pull_request.labels.*.name) }}"

    - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"