on:
  pull_request:
   types: [labeled]

jobs:
  request_colony:
    name: Request a new colony when PR is labeled with 'beehive'
    if: github.event.label.name == 'beehive'
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: |
        echo "Added a ${{ toJson(github.event.label.name) }} label to the PR"

    - name: Set beehive text
      uses: actions/github-script@v2
      id: beehive-text
      with:
        script: return "-------------------------------\nhey\nwhatsup!"
        result-encoding: string

    - name: Get result
      run: echo "${{steps.beehive-text.outputs.result}}"

    - name: get PR description
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr_url = context.payload.pull_request.url
          const result = await github.request(pr_url)
          const description_text = result.data.body
          const beehive_text = "hey"
          const updated_pr_description = description_text + beehive_text
          console.log(updated_pr_description)
