on:
  pull_request:
   types: [labeled]

jobs:
  request_colony:
    name: Request a new colony when PR is labeled with 'beehive'
    if: github.event.label.name == 'beehive'
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: |
        echo "Added a ${{ toJson(github.event.label.name) }} label to the PR"

    - name: get PR description
      uses: actions/github-script@v2
      env:
        PR_HREF: toJson(github.event.pull_request.self.href)
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const diff_url = ${env.PR_HREF}
          const result = await github.request(diff_url)
          console.log(result)