on:
  pull_request:
   types: [labeled]

jobs:
  request_colony:
    name: Request a new colony when PR is labeled with 'beehive'
    if: github.event.label.name == 'beehive'
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: |
        echo "${{ toJson(github.event.label.name) }}"

    - name: Dump GitHub context
      run: |
        echo "${{ toJson(github) }}"